export const SHOPS_SEARCH_REQUEST = 'SHOPS_SEARCH_REQUEST';
export const SHOPS_SEARCH_SUCCESS = 'SHOPS_SEARCH_SUCCESS';
export const SHOPS_SEARCH_FAIL = 'SHOPS_SEARCH_FAIL';

export const SHOPS_SEARCH_ByID_REQUEST = 'SHOPS_SEARCH_ByID_REQUEST';
export const SHOPS_SEARCH_ByID_SUCCESS = 'SHOPS_SEARCH_ByID_SUCCESS';
export const SHOPS_SEARCH_ByID_FAIL = 'SHOPS_SEARCH_ByID_FAIL';